version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      target: be
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI_ATLAS=mongodb+srv://harry:harry8atlas@cluster0-tj0q8.mongodb.net/jwtPractice?retryWrites=true&w=majority

  #   depends_on:
  #     - mongo

  # mongo:
  #   build:
  #     context: ./mongo
  #     target: db
  #   volumes:
  #     - ./mongodb-data:/data/db
  #   ports:
  #     - "27017:27017"
